# Generated by Django 5.1 on 2024-09-03 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mailid', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFileModel',
            fields=[
                ('studentfile_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=5)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('university', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('module_name', models.CharField(max_length=100)),
                ('total_word_count', models.IntegerField()),
                ('submission_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('assignment_file', models.FileField(upload_to='assignments/')),
                ('uploaded_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.studentmodel')),
            ],
        ),
    ]
