# Generated by Django 5.1 on 2024-09-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_studentmodel_studentfilemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='student_id',
            new_name='user_id',
        ),
    ]
