# Generated by Django 5.1 on 2024-09-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_rename_student_id_studentmodel_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsModel',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mailid', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
