# Generated by Django 5.1 on 2024-09-04 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_studentsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentsModel',
        ),
    ]
