# Generated by Django 5.1 on 2024-09-04 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_studentsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfilemodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.studentsmodel'),
        ),
    ]
