# Generated by Django 5.1 on 2024-09-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_alter_studentfilemodel_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
