# Generated by Django 5.1 on 2024-09-04 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_teachersmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerModel',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mailid', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAssignModel',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_time', models.DateTimeField()),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.teachersmodel')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.studentfilemodel')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.managermodel')),
            ],
        ),
    ]
