# Generated by Django 5.1 on 2024-09-04 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_alter_usertype_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfilemodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.usermodel'),
        ),
    ]
