# Generated by Django 5.1 on 2024-09-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_alter_studentfilemodel_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfilemodel',
            name='student',
        ),
    ]
