# Generated by Django 5.1 on 2024-09-04 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_remove_studentfilemodel_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfilemodel',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.usermodel'),
        ),
    ]
