# Generated by Django 5.1 on 2024-09-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_remove_facultyassignmodel_assigned_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentsModel',
        ),
    ]
