# Generated by Django 5.1 on 2024-09-05 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0018_delete_studentsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAssignModel',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_time', models.DateTimeField()),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Manager', to='UserApp.usermodel')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Faculty', to='UserApp.usermodel')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.studentfilemodel')),
            ],
        ),
    ]
