# Generated by Django 5.1 on 2024-09-05 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0019_facultyassignmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAnswerModel',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_file', models.FileField(upload_to='faculty_answers/')),
                ('uploaded_date', models.DateTimeField()),
                ('assigned_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserApp.facultyassignmodel')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerErrorFileModel',
            fields=[
                ('error_id', models.AutoField(primary_key=True, serialize=False)),
                ('error_file', models.FileField(blank=True, null=True, upload_to='manager_errors/')),
                ('error_description', models.TextField(blank=True, null=True)),
                ('uploaded_date', models.DateTimeField()),
                ('faculty_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserApp.facultyanswermodel')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.usermodel')),
            ],
        ),
    ]
