# Generated by Django 5.1 on 2024-09-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0020_facultyanswermodel_managererrorfilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managererrorfilemodel',
            name='error_description',
        ),
    ]
