# Generated by Django 5.1 on 2024-09-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0021_remove_managererrorfilemodel_error_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyanswermodel',
            name='status',
            field=models.CharField(choices=[('Verifying', 'Verifying'), ('Error', 'Error'), ('Completed', 'Completed')], default='Verifying', max_length=20),
        ),
    ]
