# Generated by Django 5.1 on 2024-09-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0022_facultyanswermodel_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
