# Generated by Django 5.1 on 2024-09-10 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0023_delete_filemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCodeModel',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.IntegerField()),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentUploadsModel',
            fields=[
                ('studentfile_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=5)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('university', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('module_name', models.CharField(max_length=100)),
                ('total_word_count', models.IntegerField()),
                ('submission_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('assignment_file', models.FileField(upload_to='assignments/')),
                ('model_work', models.FileField(upload_to='model-work/')),
                ('module_materials', models.FileField(upload_to='module_materials/')),
                ('instructions', models.FileField(upload_to='instructions/')),
                ('uploaded_date', models.DateField()),
                ('country_specific', models.BooleanField(default=False)),
                ('country_specific_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_specific', models.BooleanField(default=False)),
                ('company_specific_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mailid', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.usertype')),
            ],
        ),
    ]
