# Generated by Django 5.1 on 2024-09-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0024_countrycodemodel_studentuploadsmodel_usersmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrycodemodel',
            name='country_code',
            field=models.CharField(max_length=50),
        ),
    ]
