# Generated by Django 5.1 on 2024-09-10 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0025_alter_countrycodemodel_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismModel',
            fields=[
                ('error_id', models.AutoField(primary_key=True, serialize=False)),
                ('plagiarism_report', models.FileField(blank=True, null=True, upload_to='manager_errors/')),
                ('ai_report', models.FileField(blank=True, null=True, upload_to='plagiarism_report/')),
                ('proof_reading', models.FileField(blank=True, null=True, upload_to='proof_reading/')),
                ('uploaded_date', models.DateTimeField()),
                ('faculty_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserApp.facultyanswermodel')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.usersmodel')),
            ],
        ),
    ]
