# Generated by Django 5.1 on 2024-09-10 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0026_plagiarismmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyassignmodel',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Manager', to='UserApp.usersmodel'),
        ),
        migrations.AlterField(
            model_name='facultyassignmodel',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Faculty', to='UserApp.usersmodel'),
        ),
        migrations.AlterField(
            model_name='facultyassignmodel',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.studentuploadsmodel'),
        ),
        migrations.AlterField(
            model_name='studentuploadsmodel',
            name='instructions',
            field=models.FileField(blank=True, null=True, upload_to='instructions/'),
        ),
        migrations.AlterField(
            model_name='studentuploadsmodel',
            name='model_work',
            field=models.FileField(blank=True, null=True, upload_to='model-work/'),
        ),
        migrations.AlterField(
            model_name='studentuploadsmodel',
            name='module_materials',
            field=models.FileField(blank=True, null=True, upload_to='module_materials/'),
        ),
        migrations.AlterField(
            model_name='studentuploadsmodel',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.usersmodel'),
        ),
    ]
