# Generated by Django 5.1 on 2024-09-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0028_studentuploadsmodel_countrycode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuploadsmodel',
            name='country_code',
        ),
    ]
