# Generated by Django 5.1 on 2024-09-10 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0029_remove_studentuploadsmodel_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyanswermodel',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.usersmodel'),
        ),
        migrations.AlterField(
            model_name='managererrorfilemodel',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.usersmodel'),
        ),
    ]
